name: update-module-options-workflow

on:
  push:
    branches: 
      - ci/module-list

  workflow_dispatch:
    inputs:
      yamlFilePath:
        type: string
        description: 'Path to the onboarding workflow YAML file (e.g., .github/workflows/onboarding-workflow.yml)'
        required: true
        default: '.github/workflows/onboarding-workflow.yml'

      registryUrl:
        type: string
        description: 'URL of the MCR registry'
        default: 'https://mcr.microsoft.com/v2'

      moduleRepoPath:
        type: string
        description: 'Path to the module repository in the MCR registry'
        default: 'bicep/avm/res'

  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

permissions:
  contents: write

jobs:
  update_onboarding_workflow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Fetch Module List from MCR
      - name: Fetch Module List
        id: fetch_modules
        run: |
          pwsh ./utilities/tools/Get-ModuleListFromMcr.ps1 `
            -RegistryUrl '${{ inputs.registryUrl }}' `
            -ModuleRepoPath '${{ inputs.moduleRepoPath }}' `
            > raw-module-list.txt
        shell: pwsh

      # Step 3: Format Module List
      - name: Format Module List
        id: format_modules
        run: |
          moduleList=$(cat raw-module-list.txt | jq -R -s 'split("\n") | map(select(length > 0))')
          echo "::set-output name=moduleList::${moduleList}"
        shell: bash

      # Step 4: Update Onboarding Workflow
      - name: Update Onboarding Workflow
        id: update_workflow
        run: |
          pwsh ./utilities/tools/Add-ModulesToOnboardingWorkflow.ps1 `
            -yamlFilePath '${{ inputs.yamlFilePath }}' `
            -newOptions '${{ steps.format_modules.outputs.moduleList }}'
        shell: pwsh

      # # Step 5: Validate Updated YAML
      # - name: Validate YAML File
      #   run: |
      #     yamllint '${{ inputs.yamlFilePath }}'
      #   shell: bash

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update onboarding workflow with new module options" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # # Step 7: Create Pull Request
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ci/module-list
      #     base: main
      #     title: "Update Onboarding Workflow Module Options"
      #     body: |
      #       This PR updates the onboarding workflow with the latest module options fetched from the MCR registry.
